-- GENERATED by tools/gen_schema_sql.py from db/schema.json — do not hand-edit.
-- dialect: mysql

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `settings` (
  `key_name` VARCHAR(80) NOT NULL,
  `value_type` VARCHAR(16) NOT NULL DEFAULT 'string',
  `value_text` TEXT NULL,
  `updated_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(80) NOT NULL,
  `email` VARCHAR(190) NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `display_name` VARCHAR(64) NULL,
  `role` VARCHAR(16) NOT NULL DEFAULT 'admin',
  `locale` VARCHAR(5) NOT NULL DEFAULT 'ar',
  `xp` INT NOT NULL DEFAULT 0,
  `disabled_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_username` (`username`),
  UNIQUE KEY `uq_users_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sessions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `token_hash` VARCHAR(64) NOT NULL,
  `ip` VARCHAR(45) NULL,
  `data_json` LONGTEXT NULL,
  `last_seen_at` DATETIME NOT NULL,
  `expires_at` DATETIME NOT NULL,
  CONSTRAINT `fk_sessions_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sessions_token_hash` (`token_hash`),
  KEY `idx_sessions_expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(80) NOT NULL,
  `name_ar` VARCHAR(96) NOT NULL,
  `name_en` VARCHAR(96) NOT NULL,
  `color` VARCHAR(16) NOT NULL DEFAULT '#7c5cff',
  `parent_id` INT NULL,
  `position` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  CONSTRAINT `fk_categories_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_categories_slug` (`slug`),
  KEY `idx_categories_position` (`position`),
  KEY `idx_categories_parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `games` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(80) NOT NULL,
  `slug_ar` VARCHAR(80) NULL,
  `title_ar` VARCHAR(120) NOT NULL,
  `title_en` VARCHAR(120) NOT NULL,
  `desc_ar` TEXT NULL,
  `desc_en` TEXT NULL,
  `howto_ar` TEXT NULL,
  `howto_en` TEXT NULL,
  `category_id` INT NULL,
  `kind` VARCHAR(12) NOT NULL DEFAULT 'feed',
  `provider` VARCHAR(32) NOT NULL DEFAULT 'own',
  `external_id` VARCHAR(64) NULL,
  `embed_url` VARCHAR(255) NOT NULL DEFAULT '',
  `local_path` VARCHAR(190) NOT NULL DEFAULT '',
  `runtime_module` VARCHAR(64) NOT NULL DEFAULT '',
  `poster_path` VARCHAR(190) NOT NULL DEFAULT '',
  `aspect` VARCHAR(8) NOT NULL DEFAULT '16/9',
  `devices` VARCHAR(48) NOT NULL DEFAULT 'desktop,mobile,tablet',
  `controls` VARCHAR(48) NOT NULL DEFAULT 'pointer',
  `players` VARCHAR(12) NOT NULL DEFAULT 'solo',
  `age_rating` VARCHAR(12) NOT NULL DEFAULT 'all',
  `kid_friendly` TINYINT(1) NOT NULL DEFAULT 1,
  `featured` TINYINT(1) NOT NULL DEFAULT 0,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `plays_count` INT NOT NULL DEFAULT 0,
  `plays_7d` INT NOT NULL DEFAULT 0,
  `likes_count` INT NOT NULL DEFAULT 0,
  `rating_sum` INT NOT NULL DEFAULT 0,
  `rating_count` INT NOT NULL DEFAULT 0,
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  CONSTRAINT `fk_games_category_id` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_games_slug` (`slug`),
  UNIQUE KEY `uq_games_provider_external_id` (`provider`, `external_id`),
  KEY `idx_games_status` (`status`),
  KEY `idx_games_category_id` (`category_id`),
  KEY `idx_games_featured_plays_count` (`featured`, `plays_count`),
  KEY `idx_games_kind` (`kind`),
  KEY `idx_games_plays_7d` (`plays_7d`),
  FULLTEXT KEY `ft_games` (`title_ar`, `title_en`, `desc_ar`, `desc_en`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `game_licenses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  `provider` VARCHAR(32) NOT NULL DEFAULT 'own',
  `external_id` VARCHAR(64) NULL,
  `license_type` VARCHAR(16) NOT NULL,
  `license_ref` VARCHAR(48) NOT NULL,
  `upstream_repo` VARCHAR(190) NOT NULL DEFAULT '',
  `commit_sha` VARCHAR(40) NOT NULL DEFAULT '',
  `license_path` VARCHAR(190) NOT NULL DEFAULT '',
  `license_file` VARCHAR(190) NOT NULL DEFAULT '',
  `license_sha256` VARCHAR(64) NOT NULL DEFAULT '',
  `proof_url` VARCHAR(255) NOT NULL DEFAULT '',
  `invoice_ref` VARCHAR(64) NOT NULL DEFAULT '',
  `allow_origins` VARCHAR(255) NOT NULL DEFAULT '',
  `attribution_required` TINYINT(1) NOT NULL DEFAULT 0,
  `attribution_html` TEXT NULL,
  `captured_at` DATE NULL,
  `expires_at` DATE NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  CONSTRAINT `fk_game_licenses_game_id` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON DELETE CASCADE,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_game_licenses_game_id_provider_external_id` (`game_id`, `provider`, `external_id`),
  KEY `idx_game_licenses_status` (`status`),
  KEY `idx_game_licenses_license_type` (`license_type`),
  KEY `idx_game_licenses_expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `takedowns` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_id` INT NULL,
  `slug_claim` VARCHAR(80) NOT NULL DEFAULT '',
  `reporter_name` VARCHAR(120) NOT NULL,
  `reporter_email` VARCHAR(190) NOT NULL,
  `reporter_org` VARCHAR(120) NULL,
  `work_title` VARCHAR(190) NOT NULL,
  `work_url` VARCHAR(255) NULL,
  `our_url` VARCHAR(255) NOT NULL,
  `basis` VARCHAR(16) NOT NULL DEFAULT 'copyright',
  `statement_good_faith` TINYINT(1) NOT NULL DEFAULT 0,
  `statement_under_penalty` TINYINT(1) NOT NULL DEFAULT 0,
  `signature` VARCHAR(190) NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'open',
  `counter_notice` TEXT NULL,
  `action_taken` VARCHAR(190) NULL,
  `received_at` DATETIME NOT NULL,
  `resolved_at` DATETIME NULL,
  `handled_by` INT NULL,
  CONSTRAINT `fk_takedowns_game_id` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_takedowns_handled_by` FOREIGN KEY (`handled_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`),
  KEY `idx_takedowns_status_received_at` (`status`, `received_at`),
  KEY `idx_takedowns_game_id` (`game_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `takedown_notices` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `takedown_id` INT NOT NULL,
  `channel` VARCHAR(16) NOT NULL DEFAULT 'email',
  `recipient` VARCHAR(190) NOT NULL,
  `subject` VARCHAR(190) NOT NULL,
  `body` TEXT NOT NULL,
  `sent_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  CONSTRAINT `fk_takedown_notices_takedown_id` FOREIGN KEY (`takedown_id`) REFERENCES `takedowns` (`id`) ON DELETE CASCADE,
  PRIMARY KEY (`id`),
  KEY `idx_takedown_notices_takedown_id` (`takedown_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `audit_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `actor_label` VARCHAR(64) NOT NULL DEFAULT 'system',
  `action` VARCHAR(48) NOT NULL,
  `entity` VARCHAR(32) NOT NULL,
  `entity_id` INT NULL,
  `payload` LONGTEXT NULL,
  `ip` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_log_entity_entity_id` (`entity`, `entity_id`),
  KEY `idx_audit_log_action` (`action`),
  KEY `idx_audit_log_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(80) NOT NULL,
  `name_ar` VARCHAR(64) NOT NULL,
  `name_en` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tags_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `game_tag` (
  `game_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  CONSTRAINT `fk_game_tag_game_id` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_game_tag_tag_id` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`) ON DELETE CASCADE,
  PRIMARY KEY (`game_id`, `tag_id`),
  KEY `idx_game_tag_tag_id` (`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `collections` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(80) NOT NULL,
  `title_ar` VARCHAR(120) NOT NULL,
  `title_en` VARCHAR(120) NOT NULL,
  `blurb_ar` TEXT NULL,
  `blurb_en` TEXT NULL,
  `auto_rule` VARCHAR(190) NULL,
  `is_auto` TINYINT(1) NOT NULL DEFAULT 0,
  `position` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_collections_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `collection_game` (
  `collection_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  `position` INT NOT NULL DEFAULT 0,
  CONSTRAINT `fk_collection_game_collection_id` FOREIGN KEY (`collection_id`) REFERENCES `collections` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_collection_game_game_id` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON DELETE CASCADE,
  PRIMARY KEY (`collection_id`, `game_id`),
  KEY `idx_collection_game_game_id` (`game_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `favorites` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `device_key` VARCHAR(64) NULL,
  `game_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  CONSTRAINT `fk_favorites_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_favorites_game_id` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON DELETE CASCADE,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_favorites_user_id_game_id` (`user_id`, `game_id`),
  UNIQUE KEY `uq_favorites_device_key_game_id` (`device_key`, `game_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `play_events` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  `device_key` VARCHAR(64) NULL,
  `source` VARCHAR(16) NOT NULL DEFAULT 'site',
  `seconds` INT NOT NULL DEFAULT 0,
  `completed` TINYINT(1) NOT NULL DEFAULT 0,
  `played_at` DATETIME NOT NULL,
  CONSTRAINT `fk_play_events_game_id` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON DELETE CASCADE,
  PRIMARY KEY (`id`),
  KEY `idx_play_events_game_id_played_at` (`game_id`, `played_at`),
  KEY `idx_play_events_played_at` (`played_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `leaderboard` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  `user_id` INT NULL,
  `alias` VARCHAR(48) NULL,
  `score` INT NOT NULL,
  `period` VARCHAR(8) NOT NULL DEFAULT 'all',
  `period_key` VARCHAR(12) NOT NULL DEFAULT 'all',
  `week_key` VARCHAR(12) NOT NULL DEFAULT '',
  `signature` VARCHAR(64) NULL,
  `submitted_at` DATETIME NOT NULL,
  CONSTRAINT `fk_leaderboard_game_id` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_leaderboard_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_leaderboard_game_id_user_id_period_period_key` (`game_id`, `user_id`, `period`, `period_key`),
  UNIQUE KEY `uq_leaderboard_game_id_alias_period_period_key` (`game_id`, `alias`, `period`, `period_key`),
  KEY `idx_leaderboard_game_id_period_period_key_score` (`game_id`, `period`, `period_key`, `score`),
  KEY `idx_leaderboard_period_period_key_score` (`period`, `period_key`, `score`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `provider_games` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `provider` VARCHAR(32) NOT NULL,
  `external_id` VARCHAR(64) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `fetched_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_provider_games_provider_external_id` (`provider`, `external_id`),
  KEY `idx_provider_games_fetched_at` (`fetched_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `provider_runs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `provider` VARCHAR(32) NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'ok',
  `rows_seen` INT NOT NULL DEFAULT 0,
  `rows_new` INT NOT NULL DEFAULT 0,
  `rows_rejected` INT NOT NULL DEFAULT 0,
  `detail` TEXT NULL,
  `started_at` DATETIME NOT NULL,
  `finished_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_provider_runs_provider_started_at` (`provider`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ads_slots` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slot_key` VARCHAR(32) NOT NULL,
  `client` VARCHAR(32) NOT NULL,
  `slot_id` VARCHAR(32) NOT NULL,
  `format` VARCHAR(16) NOT NULL DEFAULT 'responsive',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ads_slots_slot_key` (`slot_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ad_impressions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slot_key` VARCHAR(32) NOT NULL,
  `game_id` INT NULL,
  `day` DATE NOT NULL,
  `views` INT NOT NULL DEFAULT 0,
  `clicks` INT NOT NULL DEFAULT 0,
  CONSTRAINT `fk_ad_impressions_game_id` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ad_impressions_slot_key_game_id_day` (`slot_key`, `game_id`, `day`),
  KEY `idx_ad_impressions_day` (`day`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `xp_events` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_key` VARCHAR(64) NOT NULL,
  `game_id` INT NULL,
  `amount` INT NOT NULL,
  `reason` VARCHAR(24) NOT NULL,
  `created_at` DATETIME NOT NULL,
  CONSTRAINT `fk_xp_events_game_id` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`),
  KEY `idx_xp_events_device_key_created_at` (`device_key`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `badges` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(80) NOT NULL,
  `name_ar` VARCHAR(64) NOT NULL,
  `name_en` VARCHAR(64) NOT NULL,
  `rule_json` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_badges_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_badges` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_key` VARCHAR(64) NOT NULL,
  `badge_id` INT NOT NULL,
  `awarded_at` DATETIME NOT NULL,
  CONSTRAINT `fk_user_badges_badge_id` FOREIGN KEY (`badge_id`) REFERENCES `badges` (`id`) ON DELETE CASCADE,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_badges_device_key_badge_id` (`device_key`, `badge_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `i18n_overrides` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `locale` VARCHAR(5) NOT NULL,
  `string_key` VARCHAR(96) NOT NULL,
  `value` TEXT NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_i18n_overrides_locale_string_key` (`locale`, `string_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `schema_version` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `version` INT NOT NULL,
  `note` VARCHAR(190) NOT NULL DEFAULT '',
  `applied_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_schema_version_version` (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
