-- GENERATED by tools/gen_schema_sql.py from db/schema.json — do not hand-edit.
-- dialect: sqlite

-- Nawras\Db\Connection opens SQLite with PRAGMA foreign_keys = ON.

CREATE TABLE IF NOT EXISTS "settings" (
  "key_name" TEXT NOT NULL,
  "value_type" TEXT NOT NULL DEFAULT 'string',
  "value_text" TEXT NULL,
  "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "username" TEXT NOT NULL,
  "email" TEXT NULL,
  "password_hash" TEXT NOT NULL,
  "display_name" TEXT NULL,
  "role" TEXT NOT NULL DEFAULT 'admin',
  "locale" TEXT NOT NULL DEFAULT 'ar',
  "xp" INTEGER NOT NULL DEFAULT 0,
  "disabled_at" TEXT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username ON "users" ("username");
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON "users" ("email");

CREATE TABLE IF NOT EXISTS "sessions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "user_id" INTEGER NULL REFERENCES "users" ("id") ON DELETE SET NULL,
  "token_hash" TEXT NOT NULL,
  "ip" TEXT NULL,
  "data_json" TEXT NULL,
  "last_seen_at" TEXT NOT NULL,
  "expires_at" TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sessions_token_hash ON "sessions" ("token_hash");
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON "sessions" ("expires_at");

CREATE TABLE IF NOT EXISTS "categories" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "slug" TEXT NOT NULL,
  "name_ar" TEXT NOT NULL,
  "name_en" TEXT NOT NULL,
  "color" TEXT NOT NULL DEFAULT '#7c5cff',
  "parent_id" INTEGER NULL REFERENCES "categories" ("id") ON DELETE SET NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_categories_slug ON "categories" ("slug");
CREATE INDEX IF NOT EXISTS idx_categories_position ON "categories" ("position");
CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON "categories" ("parent_id");

CREATE TABLE IF NOT EXISTS "games" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "slug" TEXT NOT NULL,
  "slug_ar" TEXT NULL,
  "title_ar" TEXT NOT NULL,
  "title_en" TEXT NOT NULL,
  "desc_ar" TEXT NULL,
  "desc_en" TEXT NULL,
  "howto_ar" TEXT NULL,
  "howto_en" TEXT NULL,
  "category_id" INTEGER NULL REFERENCES "categories" ("id") ON DELETE SET NULL,
  "kind" TEXT NOT NULL DEFAULT 'feed',
  "provider" TEXT NOT NULL DEFAULT 'own',
  "external_id" TEXT NULL,
  "embed_url" TEXT NOT NULL DEFAULT '',
  "local_path" TEXT NOT NULL DEFAULT '',
  "runtime_module" TEXT NOT NULL DEFAULT '',
  "poster_path" TEXT NOT NULL DEFAULT '',
  "aspect" TEXT NOT NULL DEFAULT '16/9',
  "devices" TEXT NOT NULL DEFAULT 'desktop,mobile,tablet',
  "controls" TEXT NOT NULL DEFAULT 'pointer',
  "players" TEXT NOT NULL DEFAULT 'solo',
  "age_rating" TEXT NOT NULL DEFAULT 'all',
  "kid_friendly" INTEGER NOT NULL DEFAULT 1,
  "featured" INTEGER NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "plays_count" INTEGER NOT NULL DEFAULT 0,
  "plays_7d" INTEGER NOT NULL DEFAULT 0,
  "likes_count" INTEGER NOT NULL DEFAULT 0,
  "rating_sum" INTEGER NOT NULL DEFAULT 0,
  "rating_count" INTEGER NOT NULL DEFAULT 0,
  "published_at" TEXT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_games_slug ON "games" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS uq_games_provider_external_id ON "games" ("provider", "external_id");
CREATE INDEX IF NOT EXISTS idx_games_status ON "games" ("status");
CREATE INDEX IF NOT EXISTS idx_games_category_id ON "games" ("category_id");
CREATE INDEX IF NOT EXISTS idx_games_featured_plays_count ON "games" ("featured", "plays_count");
CREATE INDEX IF NOT EXISTS idx_games_kind ON "games" ("kind");
CREATE INDEX IF NOT EXISTS idx_games_plays_7d ON "games" ("plays_7d");

CREATE TABLE IF NOT EXISTS "game_licenses" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "game_id" INTEGER NOT NULL REFERENCES "games" ("id") ON DELETE CASCADE,
  "provider" TEXT NOT NULL DEFAULT 'own',
  "external_id" TEXT NULL,
  "license_type" TEXT NOT NULL,
  "license_ref" TEXT NOT NULL,
  "upstream_repo" TEXT NOT NULL DEFAULT '',
  "commit_sha" TEXT NOT NULL DEFAULT '',
  "license_path" TEXT NOT NULL DEFAULT '',
  "license_file" TEXT NOT NULL DEFAULT '',
  "license_sha256" TEXT NOT NULL DEFAULT '',
  "proof_url" TEXT NOT NULL DEFAULT '',
  "invoice_ref" TEXT NOT NULL DEFAULT '',
  "allow_origins" TEXT NOT NULL DEFAULT '',
  "attribution_required" INTEGER NOT NULL DEFAULT 0,
  "attribution_html" TEXT NULL,
  "captured_at" TEXT NULL,
  "expires_at" TEXT NULL,
  "status" TEXT NOT NULL DEFAULT 'active',
  "notes" TEXT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_game_licenses_game_id_provider_external_id ON "game_licenses" ("game_id", "provider", "external_id");
CREATE INDEX IF NOT EXISTS idx_game_licenses_status ON "game_licenses" ("status");
CREATE INDEX IF NOT EXISTS idx_game_licenses_license_type ON "game_licenses" ("license_type");
CREATE INDEX IF NOT EXISTS idx_game_licenses_expires_at ON "game_licenses" ("expires_at");

CREATE TABLE IF NOT EXISTS "takedowns" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "game_id" INTEGER NULL REFERENCES "games" ("id") ON DELETE SET NULL,
  "slug_claim" TEXT NOT NULL DEFAULT '',
  "reporter_name" TEXT NOT NULL,
  "reporter_email" TEXT NOT NULL,
  "reporter_org" TEXT NULL,
  "work_title" TEXT NOT NULL,
  "work_url" TEXT NULL,
  "our_url" TEXT NOT NULL,
  "basis" TEXT NOT NULL DEFAULT 'copyright',
  "statement_good_faith" INTEGER NOT NULL DEFAULT 0,
  "statement_under_penalty" INTEGER NOT NULL DEFAULT 0,
  "signature" TEXT NULL,
  "status" TEXT NOT NULL DEFAULT 'open',
  "counter_notice" TEXT NULL,
  "action_taken" TEXT NULL,
  "received_at" TEXT NOT NULL,
  "resolved_at" TEXT NULL,
  "handled_by" INTEGER NULL REFERENCES "users" ("id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_takedowns_status_received_at ON "takedowns" ("status", "received_at");
CREATE INDEX IF NOT EXISTS idx_takedowns_game_id ON "takedowns" ("game_id");

CREATE TABLE IF NOT EXISTS "takedown_notices" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "takedown_id" INTEGER NOT NULL REFERENCES "takedowns" ("id") ON DELETE CASCADE,
  "channel" TEXT NOT NULL DEFAULT 'email',
  "recipient" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "sent_at" TEXT NULL,
  "created_at" TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_takedown_notices_takedown_id ON "takedown_notices" ("takedown_id");

CREATE TABLE IF NOT EXISTS "audit_log" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "actor_label" TEXT NOT NULL DEFAULT 'system',
  "action" TEXT NOT NULL,
  "entity" TEXT NOT NULL,
  "entity_id" INTEGER NULL,
  "payload" TEXT NULL,
  "ip" TEXT NULL,
  "created_at" TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_log_entity_entity_id ON "audit_log" ("entity", "entity_id");
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON "audit_log" ("action");
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON "audit_log" ("created_at");

CREATE TABLE IF NOT EXISTS "tags" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "slug" TEXT NOT NULL,
  "name_ar" TEXT NOT NULL,
  "name_en" TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tags_slug ON "tags" ("slug");

CREATE TABLE IF NOT EXISTS "game_tag" (
  "game_id" INTEGER NOT NULL REFERENCES "games" ("id") ON DELETE CASCADE,
  "tag_id" INTEGER NOT NULL REFERENCES "tags" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_game_tag_tag_id ON "game_tag" ("tag_id");

CREATE TABLE IF NOT EXISTS "collections" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "slug" TEXT NOT NULL,
  "title_ar" TEXT NOT NULL,
  "title_en" TEXT NOT NULL,
  "blurb_ar" TEXT NULL,
  "blurb_en" TEXT NULL,
  "auto_rule" TEXT NULL,
  "is_auto" INTEGER NOT NULL DEFAULT 0,
  "position" INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_collections_slug ON "collections" ("slug");

CREATE TABLE IF NOT EXISTS "collection_game" (
  "collection_id" INTEGER NOT NULL REFERENCES "collections" ("id") ON DELETE CASCADE,
  "game_id" INTEGER NOT NULL REFERENCES "games" ("id") ON DELETE CASCADE,
  "position" INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_collection_game_game_id ON "collection_game" ("game_id");

CREATE TABLE IF NOT EXISTS "favorites" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "user_id" INTEGER NULL REFERENCES "users" ("id") ON DELETE SET NULL,
  "device_key" TEXT NULL,
  "game_id" INTEGER NOT NULL REFERENCES "games" ("id") ON DELETE CASCADE,
  "created_at" TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_favorites_user_id_game_id ON "favorites" ("user_id", "game_id");
CREATE UNIQUE INDEX IF NOT EXISTS uq_favorites_device_key_game_id ON "favorites" ("device_key", "game_id");

CREATE TABLE IF NOT EXISTS "play_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "game_id" INTEGER NOT NULL REFERENCES "games" ("id") ON DELETE CASCADE,
  "device_key" TEXT NULL,
  "source" TEXT NOT NULL DEFAULT 'site',
  "seconds" INTEGER NOT NULL DEFAULT 0,
  "completed" INTEGER NOT NULL DEFAULT 0,
  "played_at" TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_play_events_game_id_played_at ON "play_events" ("game_id", "played_at");
CREATE INDEX IF NOT EXISTS idx_play_events_played_at ON "play_events" ("played_at");

CREATE TABLE IF NOT EXISTS "leaderboard" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "game_id" INTEGER NOT NULL REFERENCES "games" ("id") ON DELETE CASCADE,
  "user_id" INTEGER NULL REFERENCES "users" ("id") ON DELETE SET NULL,
  "alias" TEXT NULL,
  "score" INTEGER NOT NULL,
  "period" TEXT NOT NULL DEFAULT 'all',
  "period_key" TEXT NOT NULL DEFAULT 'all',
  "week_key" TEXT NOT NULL DEFAULT '',
  "signature" TEXT NULL,
  "submitted_at" TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_leaderboard_game_id_user_id_period_period_key ON "leaderboard" ("game_id", "user_id", "period", "period_key");
CREATE UNIQUE INDEX IF NOT EXISTS uq_leaderboard_game_id_alias_period_period_key ON "leaderboard" ("game_id", "alias", "period", "period_key");
CREATE INDEX IF NOT EXISTS idx_leaderboard_game_id_period_period_key_score ON "leaderboard" ("game_id", "period", "period_key", "score");
CREATE INDEX IF NOT EXISTS idx_leaderboard_period_period_key_score ON "leaderboard" ("period", "period_key", "score");

CREATE TABLE IF NOT EXISTS "provider_games" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "provider" TEXT NOT NULL,
  "external_id" TEXT NOT NULL,
  "payload" TEXT NOT NULL,
  "fetched_at" TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_provider_games_provider_external_id ON "provider_games" ("provider", "external_id");
CREATE INDEX IF NOT EXISTS idx_provider_games_fetched_at ON "provider_games" ("fetched_at");

CREATE TABLE IF NOT EXISTS "provider_runs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "provider" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'ok',
  "rows_seen" INTEGER NOT NULL DEFAULT 0,
  "rows_new" INTEGER NOT NULL DEFAULT 0,
  "rows_rejected" INTEGER NOT NULL DEFAULT 0,
  "detail" TEXT NULL,
  "started_at" TEXT NOT NULL,
  "finished_at" TEXT NULL
);
CREATE INDEX IF NOT EXISTS idx_provider_runs_provider_started_at ON "provider_runs" ("provider", "started_at");

CREATE TABLE IF NOT EXISTS "ads_slots" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "slot_key" TEXT NOT NULL,
  "client" TEXT NOT NULL,
  "slot_id" TEXT NOT NULL,
  "format" TEXT NOT NULL DEFAULT 'responsive',
  "enabled" INTEGER NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ads_slots_slot_key ON "ads_slots" ("slot_key");

CREATE TABLE IF NOT EXISTS "ad_impressions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "slot_key" TEXT NOT NULL,
  "game_id" INTEGER NULL REFERENCES "games" ("id") ON DELETE SET NULL,
  "day" TEXT NOT NULL,
  "views" INTEGER NOT NULL DEFAULT 0,
  "clicks" INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ad_impressions_slot_key_game_id_day ON "ad_impressions" ("slot_key", "game_id", "day");
CREATE INDEX IF NOT EXISTS idx_ad_impressions_day ON "ad_impressions" ("day");

CREATE TABLE IF NOT EXISTS "xp_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "device_key" TEXT NOT NULL,
  "game_id" INTEGER NULL REFERENCES "games" ("id") ON DELETE SET NULL,
  "amount" INTEGER NOT NULL,
  "reason" TEXT NOT NULL,
  "created_at" TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_xp_events_device_key_created_at ON "xp_events" ("device_key", "created_at");

CREATE TABLE IF NOT EXISTS "badges" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "slug" TEXT NOT NULL,
  "name_ar" TEXT NOT NULL,
  "name_en" TEXT NOT NULL,
  "rule_json" TEXT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_badges_slug ON "badges" ("slug");

CREATE TABLE IF NOT EXISTS "user_badges" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "device_key" TEXT NOT NULL,
  "badge_id" INTEGER NOT NULL REFERENCES "badges" ("id") ON DELETE CASCADE,
  "awarded_at" TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_badges_device_key_badge_id ON "user_badges" ("device_key", "badge_id");

CREATE TABLE IF NOT EXISTS "i18n_overrides" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "locale" TEXT NOT NULL,
  "string_key" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_i18n_overrides_locale_string_key ON "i18n_overrides" ("locale", "string_key");

CREATE TABLE IF NOT EXISTS "schema_version" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "version" INTEGER NOT NULL,
  "note" TEXT NOT NULL DEFAULT '',
  "applied_at" TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_schema_version_version ON "schema_version" ("version");
